# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: mssql-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/docker/volumes
  claimRef:
    name: mssql-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  # volumeName: mssql-pv
  accessModes:
    - ReadWriteOnce